### ISSUE TITLE
Error on Anki 23.10.1 

### ISSUE THREAD

**Issue by brimwats** [abdnh/anki-batch-csv-importer#1]
Anki 23.10.1 (fac9e0ee) Python 3.9.15 Qt 6.6.0 PyQt 6.6.0
Platform: Windows-10-10.0.22621
Flags: frz=True ao=True sv=3
Add-ons, last update check: 2023-11-20 14:45:14

When loading Batch CSV Importer:
Traceback (most recent call last):
  File "aqt.addons", line 245, in loadAddons
  File "C:\Users\bri\AppData\Roaming\Anki2\addons21\998454778\__init__.py", line 9, in <module>
    from aqt.import_export.import_csv_dialog import ImportCsvDialog
ModuleNotFoundError: No module named 'aqt.import_export.import_csv_dialog'

**Comment by abdnh** [comment]
It's no longer possible to make the add-on work with the Anki's CSV import screen due to changes in 2.1.66. I might look into suggesting changes to Anki directly to make this possible again, but that will take me a while.
